# NUMPY-NUMERICAL PYTHON

## its n-dimensional array

In [1]:
#importing numpy
import numpy as np

In [4]:
arr=np.array(([1,2,3],[4,5,6]))

In [5]:
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [6]:
type(arr)

numpy.ndarray

In [7]:
arr.shape

(2, 3)

In [8]:
arr.ndim

2

In [9]:
arr.size

6

In [15]:
arr1=np.array(([1,2,3]))
# 1-dimensional gives shape as (3,) which shows it is 1-D array

In [13]:
arr1

array([1, 2, 3])

In [14]:
arr1.shape

(3,)

In [18]:
arr1=np.array(([1,2,3],[4,5,6]),dtype='float')
# creating numpy array as data type of float

In [17]:
arr1

array([[1., 2., 3.],
       [4., 5., 6.]])

In [21]:
z=np.zeros((3,4))
# creating a matrix of zeros by just givigng dimensions

In [22]:
z

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [23]:
o=np.ones((3,5))
# creating a matrix of ones by just givigng dimensions
o

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [25]:
np.eye(3)
#creating identity matrix

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [27]:
# for knwoign the documentation of any function
np.arange?
#then shift+enter

In [30]:
#creating a sequence of 0 to 30 with step of 5.
a=np.arange(0,30,5)
a

array([ 0,  5, 10, 15, 20, 25])

In [31]:
#creating a sequence of 10 values in range  0 to 5
a=np.linspace(0,5,10)
a

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

In [33]:
# creating an array with randome values
a=np.random.random((3,4))
a

array([[0.56750131, 0.55788115, 0.6616577 , 0.30763135],
       [0.4872433 , 0.89840316, 0.74348035, 0.27392037],
       [0.63099001, 0.92266396, 0.50113743, 0.26783132]])

In [34]:
arr=np.array(([1,2,3,4],[2,3,4,5],[5,6,7,8]))
# for reshaping the dimensions
arr.reshape(2,2,3)

array([[[1, 2, 3],
        [4, 2, 3]],

       [[4, 5, 5],
        [6, 7, 8]]])

In [36]:
arr.flatten()
# jut converting multidimension to single array

array([1, 2, 3, 4, 2, 3, 4, 5, 5, 6, 7, 8])

In [38]:
arr[1:,:3]
# in array slicing arr[x,y] where x denotes rows . in that also 1:_ shows from 1st row to end whie in y denotes columns. in which _:3 shows from first colum till 2nd column.

array([[2, 3, 4],
       [5, 6, 7]])

In [40]:
arr[1::2,:3:2]
# here 2 is step size to skip some of rows or columns

array([[2, 4]])

In [41]:
'''so overall we have for rows[start,end,step] and for columns also col[start,end,step]'''

'so overall we have for rows[start,end,step] and for columns also col[start,end,step]'

In [42]:
# for basic operation in numpy
# +,-,*,%,**,//

In [43]:
arr+1

array([[2, 3, 4, 5],
       [3, 4, 5, 6],
       [6, 7, 8, 9]])

In [44]:
arr-3

array([[-2, -1,  0,  1],
       [-1,  0,  1,  2],
       [ 2,  3,  4,  5]])

In [46]:
arr.T
# transpose

array([[1, 2, 5],
       [2, 3, 6],
       [3, 4, 7],
       [4, 5, 8]])

In [47]:
arr.max()

8

In [48]:
arr.max(axis=1)

array([4, 5, 8])

In [49]:
arr.sum()

50

In [50]:
arr1=np.array(([[1, 2, 5],
       [2, 3, 6],
       [3, 4, 7],
       [4, 5, 8]]))

In [54]:
arr=arr.reshape((4,3))

In [55]:
arr+arr1

array([[ 2,  4,  8],
       [ 6,  5,  9],
       [ 7,  9, 12],
       [10, 12, 16]])

In [56]:
arr*arr1

array([[ 1,  4, 15],
       [ 8,  6, 18],
       [12, 20, 35],
       [24, 35, 64]])

In [61]:
np.sort(arr,axis=0)
# also can provide kind=type of sort you want

array([[1, 2, 3],
       [4, 2, 3],
       [4, 5, 5],
       [6, 7, 8]])

In [62]:
# stacking and spliting includes stackign tow aray together vstack means vertically and h stack means horizonatally

In [64]:
a1=np.array(([1,2],[3,4]))
a2=np.array(([5,6],[7,8]))
np.vstack((a1,a2))

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [67]:
c=np.hstack((a1,a2))

In [68]:
np.hsplit(c,2)

[array([[1, 2],
        [3, 4]]),
 array([[5, 6],
        [7, 8]])]